import { Visite } from '../../app/core/models/visite.model';

export const MOCK_VISITES: Visite[] = [
  {
    id: 'v001',
    parcelleId: 'p001',
    technicienId: 'tech001',
    date: new Date('2024-11-18T08:30:00'),
    statut: 'completee',
    etapeActuelle: 6,
    observations: {
      croissance: 'normale',
      couleurFeuilles: 'verte',
      maladiesDetectees: [],
      ravageursDetectes: [],
      stressHydrique: false,
      hauteurPlantes: 65,
      tauxCouverture: 82,
    },
    sol: { humidite: 'normal', ph: 6.4, drainage: 'bon' },
    irrigation: { type: 'Aspersion', probleme: null },
    recommandations: [
      {
        id: 'r001',
        type: 'fertilisation',
        priorite: 'normale',
        description: 'Apport d\'azote en top-dressing recommandé dans 10 jours',
        produitSuggere: 'Urée 46%',
        delaiJours: 10,
      }
    ],
    photos: [
      'https://picsum.photos/seed/visite1a/400/300',
      'https://picsum.photos/seed/visite1b/400/300',
      'https://picsum.photos/seed/visite1c/400/300',
    ],
    rapport: 'Parcelle en bon état général. Tallage satisfaisant.',
    duree: 75,
  },
  {
    id: 'v002',
    parcelleId: 'p002',
    technicienId: 'tech001',
    date: new Date('2024-11-15T09:00:00'),
    statut: 'completee',
    etapeActuelle: 6,
    observations: {
      croissance: 'faible',
      couleurFeuilles: 'jaunissante',
      maladiesDetectees: ['Pyriculariose'],
      ravageursDetectes: [],
      stressHydrique: true,
      hauteurPlantes: 55,
      tauxCouverture: 68,
    },
    sol: { humidite: 'sec', ph: 6.8, drainage: 'moyen' },
    irrigation: { type: 'Gravitaire', probleme: 'Canal principal partiellement obstrué' },
    recommandations: [
      {
        id: 'r002',
        type: 'traitement',
        priorite: 'urgente',
        description: 'Application fongicide anti-pyriculariose sous 48h',
        produitSuggere: 'Tricyclazole 75 WP',
        delaiJours: 2,
      },
      {
        id: 'r003',
        type: 'irrigation',
        priorite: 'urgente',
        description: 'Rétablir irrigation – débloquer canal principal',
        delaiJours: 1,
      }
    ],
    photos: [
      'https://picsum.photos/seed/visite2a/400/300',
      'https://picsum.photos/seed/visite2b/400/300',
    ],
    rapport: 'Situation préoccupante : stress hydrique + début pyriculariose. Intervention urgente.',
    duree: 90,
  },
  {
    id: 'v003',
    parcelleId: 'p003',
    technicienId: 'tech002',
    date: new Date('2024-11-10T07:45:00'),
    statut: 'completee',
    etapeActuelle: 6,
    observations: {
      croissance: 'faible',
      couleurFeuilles: 'brunissante',
      maladiesDetectees: ['Helminthosporiose', 'Rouille commune'],
      ravageursDetectes: ['Foreur de tige', 'Chenille légionnaire'],
      stressHydrique: false,
      hauteurPlantes: 140,
      tauxCouverture: 90,
    },
    sol: { humidite: 'humide', ph: 5.9, drainage: 'mauvais' },
    irrigation: { type: 'Goutte-à-goutte', probleme: null },
    recommandations: [
      {
        id: 'r004',
        type: 'traitement',
        priorite: 'urgente',
        description: 'Traitement insecticide + fongicide combiné immédiat',
        produitSuggere: 'Lambda-cyhalothrine + Propiconazole',
        delaiJours: 1,
      },
      {
        id: 'r005',
        type: 'surveillance',
        priorite: 'normale',
        description: 'Suivi quotidien des chenilles légionnaires',
        delaiJours: 7,
      }
    ],
    photos: [
      'https://picsum.photos/seed/visite3a/400/300',
      'https://picsum.photos/seed/visite3b/400/300',
      'https://picsum.photos/seed/visite3c/400/300',
      'https://picsum.photos/seed/visite3d/400/300',
    ],
    rapport: 'Parcelle en situation urgente. Double attaque ravageurs + maladies fongiques.',
    duree: 120,
  },
  {
    id: 'v004',
    parcelleId: 'p004',
    technicienId: 'tech003',
    date: new Date('2024-11-17T10:00:00'),
    statut: 'completee',
    etapeActuelle: 6,
    observations: {
      croissance: 'excellente',
      couleurFeuilles: 'verte',
      maladiesDetectees: [],
      ravageursDetectes: [],
      stressHydrique: false,
      hauteurPlantes: 55,
      tauxCouverture: 95,
    },
    sol: { humidite: 'normal', ph: 6.2, drainage: 'bon' },
    irrigation: { type: 'Pluie naturelle', probleme: null },
    recommandations: [
      {
        id: 'r006',
        type: 'recolte',
        priorite: 'normale',
        description: 'Prévoir la récolte dans 3-4 semaines, gousses bien formées',
        delaiJours: 25,
      }
    ],
    photos: [
      'https://picsum.photos/seed/visite4a/400/300',
      'https://picsum.photos/seed/visite4b/400/300',
    ],
    rapport: 'Excellente campagne arachidière. Rendement prévu supérieur à la moyenne.',
    duree: 60,
  },
  {
    id: 'v005',
    parcelleId: 'p006',
    technicienId: 'tech002',
    date: new Date('2024-11-16T08:15:00'),
    statut: 'completee',
    etapeActuelle: 5,
    observations: {
      croissance: 'normale',
      couleurFeuilles: 'jaunissante',
      maladiesDetectees: ['Mildiou'],
      ravageursDetectes: ['Thrips'],
      stressHydrique: false,
      hauteurPlantes: 42,
      tauxCouverture: 75,
    },
    sol: { humidite: 'humide', ph: 6.5, drainage: 'bon' },
    irrigation: { type: 'Goutte-à-goutte', probleme: null },
    recommandations: [
      {
        id: 'r007',
        type: 'traitement',
        priorite: 'urgente',
        description: 'Traitement anti-mildiou et insecticide anti-thrips',
        produitSuggere: 'Mancozèbe + Spinosad',
        delaiJours: 3,
      }
    ],
    photos: [
      'https://picsum.photos/seed/visite5a/400/300',
    ],
    rapport: 'Début de mildiou détecté. Traitement à effectuer rapidement.',
    duree: 55,
  },
  {
    id: 'v006',
    parcelleId: 'p001',
    technicienId: 'tech001',
    date: new Date('2024-11-25T08:30:00'),
    statut: 'planifiee',
    etapeActuelle: 1,
    observations: {
      croissance: 'normale',
      couleurFeuilles: 'verte',
      maladiesDetectees: [],
      ravageursDetectes: [],
      stressHydrique: false,
      hauteurPlantes: 0,
      tauxCouverture: 0,
    },
    sol: { humidite: 'normal', ph: 0, drainage: 'bon' },
    irrigation: { type: '', probleme: null },
    recommandations: [],
    photos: [],
    rapport: null,
    duree: 0,
  },
];
